In [36]:
import numpy as np
arr=np.array([5,12,1,21,32,51])
x=arr.tolist()
print(x)


[5, 12, 1, 21, 32, 51]


In [89]:
import numpy as np
m = np.array([[0,1,2],[3,4,5],[6,7,8]])
print(m)
x = np.trace(m)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
12


In [58]:
import numpy as np
a = np.array([[1,2],[3,5]])
x=2
newarr =a[a>2]
print(newarr)
   

[3 5]


In [55]:
import numpy as np
a=np.array([[1,4,5],[3,4,6],[6,5,4]])
b=np.array([[7,8,9],[15,20,1],[2,3,6]])
c=a+b
print(c)


[[ 8 12 14]
 [18 24  7]
 [ 8  8 10]]


In [83]:
import numpy as np
a=np.matrix([[1,5,6],
             [10,30,20],
             [20,30,5]])
for i in range(len(a)):
    a[i]=a[i]-a[i].mean()
print(a)




[[ -3   1   2]
 [-10  10   0]
 [  1  11 -13]]
